
services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=guillaume
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dapp
    ports:
      - "5439:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "guillaume"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  db:
  filestore:
  mail_data:
    driver: local