# Generated by Django 5.1.7 on 2025-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42)),
                ('action', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
